name: Deploy Allure Report to GitHub Pages

on:
  workflow_run:
    workflows: ["Saa-app-testing with Allure reports"]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Download Allure report artifact
        uses: actions/github-script@v7
        with:
          script: |
            // Lataa artefakti edellisestä workflowstä
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.event.workflow_run.id }},
            });
            
            const allureArtifact = artifacts.data.artifacts.find(
              artifact => artifact.name === 'allure-report'
            );
            
            if (allureArtifact) {
              const download = await github.rest.actions.downloadArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: allureArtifact.id,
                archive_format: 'zip',
              });
              
              // Tallenna artefakti
              const fs = require('fs');
              fs.writeFileSync('allure-report.zip', Buffer.from(download.data));
            } else {
              core.setFailed('Allure report artifact not found');
            }
            
      - name: Unzip Allure report
        run: unzip -q allure-report.zip -d allure-report
        
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './allure-report'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2