name: Run Weather App Robot Framework Tests

on:
  workflow_dispatch:
    inputs:
      save_all_screenshots:
        description: 'Save all screenshots (not just failed ones)'
        required: false
        default: false
        type: boolean

jobs:
  robot-tests:
    runs-on: self-hosted

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Näytä ympäristön tiedot
      - name: Show environment info
        shell: powershell
        run: |
          Write-Host "GitHub Workspace: $env:GITHUB_WORKSPACE"
          Write-Host "Current directory:"
          pwd
          Write-Host "Python version:" 
          python --version
          Write-Host "Node.js version:"
          node --version

      # 3️⃣ Asenna Python-riippuvuudet
      - name: Install Python dependencies
        shell: powershell
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install --upgrade Appium-Python-Client robotframework robotframework-appiumlibrary

      # 4️⃣ Varmista ADB-laite
      - name: Verify ADB connection
        shell: powershell
        run: |
          adb kill-server
          adb start-server
          Start-Sleep -Seconds 2
          Write-Host "Connected devices:"
          adb devices
          $deviceCount = (adb devices | Select-Object -Skip 1 | Where-Object { $_ -match "device$" } | Measure-Object).Count
          if ($deviceCount -eq 0) {
            Write-Error "No devices connected"
            exit 1
          }

      # 5️⃣ Aja Robot Framework testit
      - name: Run Robot Framework tests
        shell: powershell
        run: |
          Write-Host "Running Robot Framework tests..."
          $screenshotParam = ""
          if ("${{ github.event.inputs.save_all_screenshots }}" -eq "true") {
            $screenshotParam = "all"
          }
          robot --outputdir robot-reports --log robot-log.html --report robot-report.html --xunit robot-xunit.xml weather_app_tests.robot
          
          if ($LASTEXITCODE -eq 0) {
            Write-Host "✅ Tests passed successfully!"
          } else {
            Write-Host "❌ Tests failed with exit code $LASTEXITCODE"
            exit $LASTEXITCODE
          }

      # 6️⃣ Lataa raportit artefaktina
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: robot-framework-reports
          path: |
            robot-reports/
            robot-log.html
            robot-report.html
            robot-xunit.xml
          retention-days: 7
