name: Run Weather App Robot Framework Tests

on:
  workflow_dispatch:
    inputs:
      save_all_screenshots:
        description: 'Save all screenshots (not just failed ones)'
        required: false
        default: false
        type: boolean

jobs:
  robot-tests:
    runs-on: self-hosted

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Näytä nykyinen hakemisto ja tiedostot debugiksi
      - name: Show current directory
        shell: powershell
        run: |
          Write-Host "Current directory:"
          pwd
          Write-Host "Files in directory:"
          ls -la

      # 3️⃣ Näytä Python-versio
      - name: Use system Python
        run: python --version

      # 4️⃣ Asenna riippuvuudet
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install --upgrade Appium-Python-Client robotframework robotframework-appiumlibrary

      # 5️⃣ Varmista ADB-laite
      - name: Verify ADB connection
        shell: powershell
        run: |
          adb kill-server
          adb start-server
          Write-Host "Connected devices:"
          adb devices
          $deviceCount = (adb devices | Select-Object -Skip 1 | Where-Object { $_ -match "device$" } | Measure-Object).Count
          if ($deviceCount -eq
