name: Run Weather App Robot Framework Tests

on:
  workflow_dispatch:
    inputs:
      save_all_screenshots:
        description: 'Save all screenshots (not just failed ones)'
        required: false
        default: false
        type: boolean

jobs:
  robot-tests:
    runs-on: self-hosted

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Näytä nykyinen hakemisto ja tiedostot debugiksi
      - name: Show current directory
        shell: powershell
        run: |
          Write-Host "Current directory before change:"
          pwd
          Write-Host "Files in directory:"
          Get-ChildItem -Force

      # 3️⃣ Vaihda repo-juureen
      - name: Change working directory to repo root
        shell: powershell
        run: |
          Set-Location $env:GITHUB_WORKSPACE
          Write-Host "Current directory after change:"
          pwd
          Write-Host "Files in directory:"
          Get-ChildItem -Force

      # 4️⃣ Näytä Python-versio
      - name: Use system Python
        run: python --version

      # 5️⃣ Asenna riippuvuudet
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip inst
